baseURL = "https://chongg039.cn/"
languageCode = "en"
title = "Co1driver 的个人博客"
theme = "river"

paginate = 10

enableRobotsTXT = true

googleAnalytics = "UA-117991024-1"

disqusShortname = "coldriver"

copyright = "Copyright 2014-{year}"
